version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - chmod +x mvnw
      - mkdir -p /tmp/maven-repository

  pre_build:
    commands:
      - echo Running tests
      - ./mvnw -Dmaven.repo.local=/tmp/maven-repository test

  build:
    commands:
      - echo Building application
      - ./mvnw -Dmaven.repo.local=/tmp/maven-repository clean package -DskipTests

artifacts:
  files:
    - target/*.zip