version: 0.2

phases:

  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - echo Running tests...
      - chmod +x mvnw
      - ./mvnw test

  build:
    commands:
      - echo Building application...
      - ./mvnw clean package

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - target/*.zip