version: '3.8'
services:
  app:
    image: coffeewiki
    ports:
      - "5000:5000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://4wpako.h.filess.io:3307/coffee_wiki_numeralsky
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: coffee_wiki_numeralsky
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
