spring.application.name=coffeewiki

server.port=5000

spring.profiles.active=prod
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=2

aws.region=${REGION}

aws.dynamodb.companies=${AWS_DYNAMODB_COMPANIES}
aws.dynamodb.products=${AWS_DYNAMODB_PRODUCTS}
encryption.secret=${ENC_KEY}
encryption.algo=${ENC_ALGO}

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_O8vlgf3aO